[package]
name = "fuel-pbft"
version = "0.1.0"
authors = ["Fuel Labs <contact@fuel.sh>"]
edition = "2021"
categories = ["cryptography::cryptocurrencies"]
edition = "2021"
homepage = "https://fuel.network/"
keywords = ["blockchain", "cryptocurrencies", "fuel-vm"]
license = "Apache-2.0"
repository = "https://github.com/FuelLabs/fuel-pbft"
description = "A pBFT scheme for the Fuel VM."

[dependencies]
fuel-tx = "0.1"
